# Generated by Django 2.1.5 on 2019-03-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_date',
            field=models.DateField(),
        ),
    ]
