# Generated by Django 2.1.5 on 2019-03-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='Name',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
